게시물, 댓글 삭제 기능 구현
boostcampwm-2021/WEB26-COKIRI pull request #112
Opened 2021-11-19 10:28 UTC by beomseok37

### 제목
게시물, 댓글 삭제 기능 구현

### 파일 변경
- frontend/src/components/Comment/index.tsx : 댓글 삭제 component추가 및 상태 반영을 위한 props 추가
- frontend/src/components/DetailPost/index.tsx : 상태 반영을 위한 props 추가
- frontend/src/components/Post/index.tsx : 상태 반영을 위한 props 추가 및 useEffect 사용
- frontend/src/components/PostComments/index.tsx :  상태 반영을 위한 props 추가
- frontend/src/components/Timeline/index.tsx : 포스트 삭제 시 상태 반영을 위한 props 추가
- frontend/src/components/buttons/deletes/CommentDeleteButton/index.tsx : 댓글 삭제 버튼 구현
- frontend/src/components/buttons/deletes/Common/index.tsx : 삭제 커먼 버튼 구현
- frontend/src/components/buttons/deletes/Common/style.ts : 삭제 커먼 버튼 스타일 적용
- frontend/src/components/buttons/deletes/PostDeleteButton/index.tsx : 포스트 삭제 버튼 구현
- frontend/src/components/modals/DeleteModal/index.tsx : 삭제 시 한 번 더 물어보는 모달 구현
- frontend/src/globals/constants.ts : 관련 상수 선언
- frontend/src/types/post.ts : 카멜 케이스 -> 파스칼 케이스
- frontend/src/utils/Fetcher.ts : 삭제 요청 구현

props 추가로 인해 file changes가 많네요.. 죄송합니다.
이번 데모에서 지적 받았던 스타일적으로 부족한 것들은 다른 피알로 올리도록 하겠습니다

2021-11-19 11:30 UTC, hyunmindev requested changes
수고하셨습니다!

2021-11-19 11:30 UTC, hyunmindev commented on frontend/src/components/Comment/index.tsx
> +          setComments={setComments}
이 부분은 `setCommets`라는 함수를 내리기 보다는 `onCommentDelete`라는 이벤트를 올리는게 좋지 않을까요~~
위에서 관리하는 것이 추상화에 더 이점이 있다고 생각합니다 😀

2021-11-19 11:30 UTC, hyunmindev commented on frontend/src/types/post.ts
> +  comments?: CommentType[];
Convention Nice~ 👍

2021-11-19 11:30 UTC, hyunmindev commented on frontend/src/types/post.ts
> +  comments?: CommentType[];
`postType` 인터페이스 명도 변경 바랍니다~

2021-11-19 11:30 UTC, hyunmindev commented on frontend/src/pages/home.tsx
> +          {isRegistered && <Timeline pages={data?.pages} onPostDelete={handlePostDelete} />}
네!! 이런식으로 특정 이벤트를 위로 올리는 방식으로 통일하면 좋을거 같네요

2021-11-19 11:30 UTC, hyunmindev commented on frontend/src/components/buttons/deletes/Common/index.tsx
> +  mutation: UseMutationResult<void, unknown, void, unknown>;
마찬가지로 뮤테이션 함수를 내리는 것이 아닌 삭제 이벤트를 올리는 방식을 활용하면 어떨까요~?

2021-11-19 14:57 UTC, beomseok37 commented on frontend/src/types/post.ts
> +  comments?: CommentType[];
왜 저는 한 번에 다 보지 못할까요... 고치겠습니다..

2021-11-19 14:58 UTC, beomseok37 commented on frontend/src/pages/home.tsx
> +          {isRegistered && <Timeline pages={data?.pages} onPostDelete={handlePostDelete} />}
아~ 알겠습니다 굳굳~~

2021-11-19 14:58 UTC, beomseok37 commented on frontend/src/components/buttons/deletes/Common/index.tsx
> +  mutation: UseMutationResult<void, unknown, void, unknown>;
넵~ 통일 시키겠습니다.

2021-11-19 15:32 UTC, hyunmindev commented on frontend/src/types/post.ts
> +  comments?: CommentType[];
자책하지마세요!! ㅋㅋㅋ 여유가 생기면 꼼꼼함이 생길거라 생각합니다!!

2021-11-20 03:14 UTC, hyunmindev approved these changes

2021-11-20 03:14 UTC, merged