오브젝트 스토리지  삭제 적용 및 mongoose 메소드 변경
boostcampwm-2021/WEB26-COKIRI pull request #99
Opened 2021-11-17 11:24 UTC by youjeonghan

### 제목
오브젝트 스토리지  삭제 적용 및 mongoose 메소드 변경

### 파일 변경
- backend/package-lock.json  패키지 설치
- backend/package.json  패키지 설치
- backend/src/routers/v1/posts.ts  import 추가
- backend/src/services/CommentLikeService.ts  mongoose delete메소드 변경
- backend/src/services/CommentService.ts  mongoose delete메소드 변경
- backend/src/services/FollowService.ts  mongoose delete메소드 변경
- backend/src/services/ImageService.ts  오브젝트 스토리지 삭제 적용
- backend/src/services/ObjectStroageService.ts  오브젝트 스토리지 삭제 서비스 코드
- backend/src/services/PostLikeService.ts  mongoose delete메소드 변경
- backend/src/services/index.ts  export 추가
- backend/src/utils/Calculate.ts  줄바꿈 추가
- backend/src/utils/Urlparser.ts  url 파서 유틸 추가
- backend/src/utils/index.ts  export 추가
- backend/src/utils/objectStorage.ts  오브젝트 스토리지 관련 유틸 코드 추가

2021-11-17 11:40 UTC, dmin0211 requested changes
👍

2021-11-17 11:40 UTC, dmin0211 commented on backend/src/routers/v1/posts.ts
> +import { ERROR, RESPONSECODE, Urlparser } from 'src/utils';
TODO URLParser 로 바꿔주세요!!

2021-11-17 11:40 UTC, dmin0211 commented on backend/src/services/ImageService.ts
> +    await Promise.all(imageUrlList);
무언가 크게 잘못 된 것 같은데요??

2021-11-17 11:40 UTC, dmin0211 commented on backend/src/utils/index.ts
> +export { default as Urlparser } from './Urlparser';
URLParser 일 것 같아요!

2021-11-17 11:40 UTC, dmin0211 commented on backend/src/utils/Calculate.ts
>  /* eslint import/prefer-default-export: 0 */
이 주석이 왜 필요한거죠?

2021-11-17 11:40 UTC, dmin0211 commented on backend/src/utils/Urlparser.ts
> +/* eslint import/prefer-default-export: 0 */
여기도요!

2021-11-17 14:54 UTC, youjeonghan commented on backend/src/routers/v1/posts.ts
> +import { ERROR, RESPONSECODE, Urlparser } from 'src/utils';
넹

2021-11-17 14:54 UTC, youjeonghan commented on backend/src/utils/index.ts
> +export { default as Urlparser } from './Urlparser';
네넹

2021-11-17 14:55 UTC, youjeonghan commented on backend/src/services/ImageService.ts
> +    await Promise.all(imageUrlList);
감사합니닷

2021-11-17 14:55 UTC, youjeonghan commented on backend/src/utils/Calculate.ts
>  /* eslint import/prefer-default-export: 0 */
예리해요!

2021-11-18 04:59 UTC, dmin0211 approved these changes

2021-11-18 05:01 UTC, merged